### ISSUE TITLE
Triple click action?

### ISSUE THREAD

**Issue by Darku87** [OriKerer/AirdotsDoubleTap#3]
Thank you so much, It works like a charm on android 10!

Would It be possible to add a triple Burton click to work as back/previous track button?

Thanks again!

**Comment by OriKerer** [comment]
Hi @Darku87, glad this app proved useful to you.
Sadly triple tap cannot be supported 'natively' (in this kind of earphones), although @taroninak added a feature on his fork to play previuos song if the media is poused.
It's not exacly triple tap; you press once to pouse the song and two more times to activate the previous song functionality.

Would you like me I can create a new release with this feature? 
(naturally I will need to test it first)

**Comment by Darku87** [comment]
That would be awesome! Thank you so much!

Is there a way so I can contribute with a small donation at least?

**Comment by OriKerer** [comment]
I've created a new release thanks to @taroninak (https://github.com/OriKerer/AirdotsDoubleTap/releases/tag/1.2).
I have also decided to upload this app to the play store to make it more accessable. I will commit the link soon.

@Darku87 Thanks for the donation offer but it is on the house ;)

Hope this helps.

**Comment by OriKerer** [comment]
Added a play store link in the README if anyone intrested :)

**Comment by taroninak** [comment]
Thanks @OriKerer will check it
