### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [OriKerer/AirdotsDoubleTap#9]
May I ask what license this app falls under? Without a license specified, it's "all rights reserved" (and "source available"). Is it FOSS (free/libre open source)? When unsure, you can e.g. refer to [spdx](https://spdx.org/licenses/) for a list of licenses and see which are approved by FSF/OSI. Thanks in advance!

**Comment by OriKerer** [comment]
Thanks, I actually did not know the "without a licence it is all rights reserved" bit.
I thought it is more like free for all.
I will go with MIT.

**Comment by IzzySoft** [comment]
Thanks a lot! I've just added your app to my repo then (should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.orik.airdotsdoubletap) around 6 pm UTC with the next sync). Updates will be fetched within 24h of your creating a new tag and attaching an APK to it. Users of my repo will then receive update notifications. Be welcome to pick [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there if you wish :smiley:

**Comment by IzzySoft** [comment]
> I actually did not know the "without a licence it is all rights reserved" bit.

Apologies, I forgot to explain that part. You wrote the code, and you published it – that only means everybody can see it. As long as you don't specify on what conditions it can be used, that's like showing your paintings in a window: I can look at them, can make a high-res photo – but am I allowed to print that and sell the poster? Only if you put a declaration next to it permitting me to do so (otherwise you could send your lawyers for copyright violation / PI infringement). Same with the code: by only publishing it you permit everyone to **see** it (and make a copy for personal use) – but if I used your code in my own software… You get the idea :wink:

Thanks again!
